server:
  port: 9191
  
spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - Path=/user/**
        filters:
        - name: CircuitBreaker
          args:
            name: USER-SERVICE
            fallbackuri: forward:/userServiceFallBackMethod
      - id: DEPARTMENT-SERVICE  
        uri: lb://DEPARTMENT-SERVICE  
        predicates:
        - Path=/department/**
        filters:
        - name: CircuitBreaker
          args:
            name: DEPARTMENT-SERVICE
            fallbackuri: forward:/departmentServiceFallBack

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutinmilliseconds=1000
  
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
